# Form implementation generated from reading ui file 'Res1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 599)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelImage = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(730, 380, 151, 151))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.labelImage.setFont(font)
        self.labelImage.setText("")
        self.labelImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelImage.setObjectName("labelImage")
        self.itemButton4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.itemButton4.setGeometry(QtCore.QRect(30, 260, 401, 41))
        self.itemButton4.setText("")
        self.itemButton4.setObjectName("itemButton4")
        self.itemButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.itemButton3.setGeometry(QtCore.QRect(30, 210, 401, 41))
        self.itemButton3.setObjectName("itemButton3")
        self.textl = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textl.setGeometry(QtCore.QRect(30, 20, 401, 61))
        self.textl.setObjectName("textl")
        self.itemButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.itemButton1.setGeometry(QtCore.QRect(30, 110, 401, 41))
        self.itemButton1.setObjectName("itemButton1")
        self.itemButton5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.itemButton5.setGeometry(QtCore.QRect(30, 310, 401, 41))
        self.itemButton5.setText("")
        self.itemButton5.setObjectName("itemButton5")
        self.itemButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.itemButton2.setGeometry(QtCore.QRect(30, 160, 401, 41))
        self.itemButton2.setObjectName("itemButton2")
        self.textl_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textl_2.setGeometry(QtCore.QRect(470, 20, 411, 331))
        self.textl_2.setObjectName("textl_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.itemButton3.setText(_translate("MainWindow", "Хорошо я все сделаю"))
        self.textl.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.6pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Сделай выбор из предложенных вариантов</span></p></body></html>"))
        self.itemButton1.setText(_translate("MainWindow", "Вы уверены что это входит в мои обязанности?"))
        self.itemButton2.setText(_translate("MainWindow", "Я не буду это делать!"))
        self.textl_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.6pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Директор сказал вам, что вы должены подготовить выступление для спонсоров проекта</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
